### ISSUE TITLE
Aud is array, not scalar value

### ISSUE THREAD

**Issue by CZechBoY** [steverhoades/oauth2-openid-connect-client#11]
Hi,
I cannot get actually validated aud field, because clientID is string and openid server sends aud as list/array.
According to rfc https://tools.ietf.org/html/rfc7519#section-4.1.3, aud is really `string[]`.
Should I send PR to validate aud against `[$clientID]`?
Am I the only one who experiences this issue?

**Comment by steverhoades** [comment]
Please provide a PR, thanks!
