### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by paulinuk** [steverhoades/oauth2-openid-connect-client#15]
Hello

I am trying to use your library but get the error

Lcobucci\JWT\Signer\Rsa\Sha256' not found in client.php:6 S

I have tried playing around with the folder structure but no luck

The folder structure downloaded via composer does not have src in it

Please can this be fixed asap?

Cheers

Paul

**Comment by steverhoades** [comment]
@paulinuk What version are you using?

**Comment by paulinuk** [comment]
The version that installs with composer

I don’t see a version number

I am basically looking for an example that I can use for authenticating with an internal identity server using OAuth open id connect with Implicity flow

**Comment by steverhoades** [comment]
Can you inspect your composer.lock file and report back the version of lcobucci/jwt that is installed?

**Comment by paulinuk** [comment]
V.0.2.0

I need something that will exchange an id token for an access token 

Does your library support that when in implicit mode?

**Comment by paulinuk** [comment]
Sorry it’s 3.3.1 was looking at the wrong one

My php is version 5.4 which I can’t update

**Comment by paulinuk** [comment]
5.4.16

**Comment by steverhoades** [comment]
@paulinuk that version of the JWT library indeed contains the class in question.
https://github.com/lcobucci/jwt/tree/3.3/src/Signer/Rsa

Can you post the full stack trace of the issue you are having?

**Comment by steverhoades** [comment]
Full disclosure that I have no tried this library on PHP 5.4. 

According to the documentation here https://github.com/thephpleague/oauth2-client/tree/2.0.0 the minimum version supported for the oauth2 client is PHP 5.5. This library is simply an extension of the oauth2-client from thephpleague. Thus I don't believe this will work for your specific use case.
