### ISSUE TITLE
The aud validation breaks the specs

### ISSUE THREAD

**Issue by automatix** [steverhoades/oauth2-openid-connect-client#16]
The ID Token's `aud` value `MAY` be an array:

[JSON Web Token (JWT) `->` 4.1.3. "aud" (Audience) Claim](https://tools.ietf.org/html/rfc7519#section-4.1.3):

> "In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value."

[OpenID Connect Core 1.0 `->` 3.1.3.7. ID Token Validation](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation)

> "Clients MUST validate the ID Token in the Token Response in the following manner:
[...] 3. [...] The aud (audience) Claim MAY contain an array with more than one element."

Currently the value gets validated by the `EqualsTo` (s. [`OpenIDConnectProvider`, L60](https://github.com/steverhoades/oauth2-openid-connect-client/blob/master/src/OpenIDConnectProvider.php#L60)). This leads to errors, if the server provides the `aud` / `aud`s as array.

Creating a PR...

**Comment by steverhoades** [comment]
MR merged and released with 0.2.1.
