### ISSUE TITLE
The aud value is a list

### ISSUE THREAD

**Issue by automatix** [steverhoades/oauth2-openid-connect-client#18]
The `aud` value is (or better: `MAY` be) a list. But it's from for auth server / provider perspective. The client knows only one `aud` value -- and its client ID.

Currently (implemented in the issue #11 / pr #13) the `aud` is an array (s. [`OpenIDConnectProvider`, L156](https://github.com/steverhoades/oauth2-openid-connect-client/blob/master/src/OpenIDConnectProvider.php#L156)). It causes errors on validation, since the `EqualsTo` (or `EqualsToOrContains`) validator expects the `§expectedValue` to be a `string`.

PR (pr #17) updated.

**Comment by steverhoades** [comment]
MR merged and released with 0.2.1.
