### ISSUE TITLE
nbf should have some tolerance

### ISSUE THREAD

**Issue by ivanrey** [steverhoades/oauth2-openid-connect-client#19]
I'm having issues with some server difference in timestamps.

The IdentityProvider gives me nbf timestamps one second in the future sometimes. I can't control their clock so there should be a setting where you could give it a little tolerance, maybe a few seconds. Right now there is no way to do this without modifying the source code directly.

**Comment by steverhoades** [comment]
@ivanrey go ahead and submit a PR and i'll give it immediate consideration.

**Comment by ivanrey** [comment]
Cool, I can think of many ways to do it. The easiest could be sending a `nbf_tolerance_seconds` (suggestions welcome), and adding it to the `$currentTime` parameter that it sends in the validation data. 

Do you think this would be an accepted way of doing it?

**Comment by ivanrey** [comment]
#20 Here's the pull request.

**Comment by steverhoades** [comment]
Released with v0.3.0. Thanks for the contribution!
