### ISSUE TITLE
AccessToken missing id_toek in jsonSerialize

### ISSUE THREAD

**Issue by fanglingsu** [steverhoades/oauth2-openid-connect-client#4]
I think it would be better to add the `id_token` also to the response of the jsonSerialize Method of the access Token. So the received, token containing the id token, could be stored in the session. Maybe you can add something like this to the AccessToken class:
```php
public function jsonSerialize()
{
    $parameters = parent::jsonSerialize();
    if ($this->idToken) {
        $parameters['id_token'] = (string)$this->idToken;
    }

    return $parameters;
}
```

**Comment by steverhoades** [comment]
@fanglingsu This looks good.  Can you provide a pull request?

**Comment by fanglingsu** [comment]
I don't have much time, so you can put it in.
