### ISSUE TITLE
v0.1.2 not available on packagist

### ISSUE THREAD

**Issue by Korikulum** [steverhoades/oauth2-openid-connect-client#5]
It seems that the latest version `v0.1.2` is not available on packagist: https://packagist.org/packages/steverhoades/oauth2-openid-connect-client.

`composer require steverhoades/oauth2-openid-connect-client` gives me `v0.1.0`.

**Comment by steverhoades** [comment]
Apologies.  I have corrected this.
https://packagist.org/packages/steverhoades/oauth2-openid-connect-client
